# Generated by Django 5.2 on 2025-05-18 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursesindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructor',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='social_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instructor',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.role'),
        ),
    ]
