# Generated by Django 5.2.1 on 2025-05-25 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_role_instructor_active_instructor_tagline_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='instructors',
            field=models.ManyToManyField(related_name='courses', to='courses.instructor'),
        ),
    ]
