# Generated by Django 5.2.1 on 2025-05-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_instructorsorderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='instructors',
        ),
    ]
