# Generated by Django 5.2.1 on 2025-05-26 19:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_instructor_photo_instructor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}, null=True),
        ),
    ]
