# Generated by Django 5.2.1 on 2025-08-03 21:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_tagsnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', 0), ('markdown', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {})}, null=True),
        ),
    ]
