# Generated by Django 5.2.7 on 2025-12-03 23:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_coursepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterpage',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', 0), ('markdown', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {})}, null=True),
        ),
        migrations.AlterField(
            model_name='segmentpage',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', 0), ('markdown', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {})}, null=True),
        ),
    ]
