# Generated by Django 5.2.7 on 2025-12-04 00:09

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_quiz_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz'),
        ),
    ]
