# Generated by Django 5.2.9 on 2025-12-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_coursematerial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentpage',
            name='aspect_ratio',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='segmentpage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentpage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
