# Generated by Django 5.2.9 on 2026-01-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_segmentpage_aspect_ratio_segmentpage_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizprogress",
            name="answers_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
