# Generated by Django 5.2.9 on 2026-01-15 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_quizprogress_answers_snapshot_alter_quiz_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instructorsorderable",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor_course",
                to="courses.instructor",
            ),
        ),
    ]
