# Generated by Django 5.2.9 on 2026-01-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_coursepage_duration_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="allowed_emails",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of email addresses allowed to access this course while it's coming soon. Staff and superusers always have access.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="coming_soon",
            field=models.TextField(
                blank=True,
                help_text="If set, this course is marked as 'Coming Soon'. Enter estimated release date (e.g., 'Spring 2026', 'March 2026'). Leave empty to make course publicly available.",
                null=True,
            ),
        ),
    ]
