# Generated by Django 5.2.9 on 2026-03-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_coursepage_allowed_emails_coursepage_coming_soon"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="code_language",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="question",
            name="code_snippet",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="choice",
            name="text",
            field=models.TextField(),
        ),
    ]
