# Generated by Django 5.2.12 on 2026-03-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0021_question_code_language_question_code_snippet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterpage",
            name="is_intro",
            field=models.BooleanField(
                default=False,
                help_text="Intro chapters are not numbered in the chapter list.",
            ),
        ),
    ]
