# Generated by Django 5.2.12 on 2026-03-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0022_chapterpage_is_intro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="code_language",
        ),
    ]
