# Generated by Django 5.2.15 on 2026-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0023_remove_question_code_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="choice",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
