# Generated by Django 5.2.17 on 2026-08-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0026_seed_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="zero_indexed_video_segments",
            field=models.BooleanField(
                default=False,
                help_text="Enable if this course's instructor numbers segments in their recorded video starting at 0 (e.g. video shows 5.0, 5.1, 5.2...). When enabled, the site's segment numbers are shifted to match.",
            ),
        ),
    ]
