# Generated by Django 5.2.17 on 2026-08-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0027_coursepage_zero_indexed_video_segments"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentpage",
            name="transcript",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
