# Generated by Django 5.2.1 on 2025-06-27 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonCoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('noncoursepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.noncoursepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.noncoursepage',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('noncoursepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.noncoursepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.noncoursepage',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('noncoursepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.noncoursepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.noncoursepage',),
        ),
        migrations.CreateModel(
            name='SponsorsPage',
            fields=[
                ('noncoursepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.noncoursepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.noncoursepage',),
        ),
    ]
