# Generated by Django 5.2.9 on 2026-01-19 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_noncoursepage_aboutpage_contactpage_newspage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessibilityPage",
            fields=[
                (
                    "noncoursepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.noncoursepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.noncoursepage",),
        ),
        migrations.CreateModel(
            name="BrandPage",
            fields=[
                (
                    "noncoursepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.noncoursepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.noncoursepage",),
        ),
    ]
