# Generated by Django 5.2.9 on 2026-01-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_accessibilitypage_brandpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspage",
            name="noncoursepage_ptr",
        ),
        migrations.DeleteModel(
            name="ContactPage",
        ),
        migrations.DeleteModel(
            name="NewsPage",
        ),
    ]
