# Generated by Django 5.2.12 on 2026-03-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="sort_order",
            field=models.IntegerField(default=1),
        ),
    ]
