name: Build, test, and deploy Python app to Azure Web App - ova

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Python and install dependencies for testing
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.13'   # or your desired version

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # # Run your tests (adjust as needed for your project)
      # - name: Run tests
      #   run: |
      #     python manage.py test

      # Azure login
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BDC97554AC094F1EB94183678407C66A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_91EFA6252ED845F8A9783C096779C5F0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_64663A89DC7B4C2B9AABCA17D2608949 }}

      # Deploy source code (not venv) to Azure; Oryx will handle requirements.txt
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ova'
          slot-name: 'Production'
          package: .
